<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.itwillbs</groupId>
	<artifactId>project</artifactId>
	<name>GIT_PROJECT</name>
	<packaging>war</packaging>
	<version>1.0.0-BUILD-SNAPSHOT</version>
	<properties>
		<java-version>11</java-version>
		<org.springframework-version>5.3.39</org.springframework-version>
		<org.aspectj-version>1.6.10</org.aspectj-version>
		<!-- Log4j2 버전 관리를 위한 프로퍼티 -->
		<log4j2-version>2.25.3</log4j2-version>
	</properties>
	<dependencies>
		<!-- Spring -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>${org.springframework-version}</version>
			<exclusions>
				<!-- Exclude Commons Logging in favor of SLF4j -->
				<exclusion>
					<groupId>commons-logging</groupId>
					<artifactId>commons-logging</artifactId>
				 </exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework-version}</version>
		</dependency>
		
		<!-- ================================================================================= -->
		<!-- 롬복(Lombok) 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.projectlombok/lombok -->
		<dependency>
		    <groupId>org.projectlombok</groupId>
		    <artifactId>lombok</artifactId>
		    <version>1.18.42</version>
		    <scope>compile</scope>
		</dependency>			
		
		<!-- =================== [데이터베이스 관련 라이브러리] ===================-->
		<!-- MySQL - JDBC 연동에 필요한 라이브러리 추가 -->
		<!-- 1. 스프링에서 JDBC 연동에 필요한 기능을 제공하는 spring-jdbc 라이브러리 -->	
		<!-- Source: https://mvnrepository.com/artifact/org.springframework/spring-jdbc -->
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-jdbc</artifactId>
		    <version>${org.springframework-version}</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- Source: https://mvnrepository.com/artifact/com.mysql/mysql-connector-j -->
		<!-- 2. MySQL Connector 추가(JDBC 드라이버) -->
		<dependency>
		    <groupId>com.mysql</groupId>
		    <artifactId>mysql-connector-j</artifactId>
		    <version>9.5.0</version>
		</dependency>
		
		<!-- 3. 커넥션 풀을 관리하는 HikariCP 라이브러리 추가(Tomcat DBCP 대용으로 사용 가능) -->
		<!-- Source: https://mvnrepository.com/artifact/com.zaxxer/HikariCP -->
		<dependency>
		    <groupId>com.zaxxer</groupId>
		    <artifactId>HikariCP</artifactId>
		    <version>7.0.2</version>
		</dependency>
		
		<!-- 4. MyBatis 활용에 필요한 라이브러리 추가 -->
		<!-- 4-1) MyBatis 기본 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.mybatis/mybatis -->
		<dependency>
		    <groupId>org.mybatis</groupId>
		    <artifactId>mybatis</artifactId>
		    <version>3.5.19</version>
		</dependency>

		<!-- 4-2) MyBatis - Spring 연동 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.mybatis/mybatis-spring -->
		<dependency>
		    <groupId>org.mybatis</groupId>
		    <artifactId>mybatis-spring</artifactId>
		    <version>2.1.2</version>
		</dependency>
		
		<!-- ================================================================================= -->
		<!-- 5. 데이터 암호화에 사용될 BCryptPasswordEncoder 클래스 포함된 라이브러리 -->
		<!-- => spring-security-core 또는 spring-security-web 등의 라이브러리 필요 -->
		<!-- Source: https://mvnrepository.com/artifact/org.springframework.security/spring-security-core -->
		<dependency>
		    <groupId>org.springframework.security</groupId>
		    <artifactId>spring-security-core</artifactId>
		    <version>5.8.16</version>
		</dependency>

		<!-- ================================================================================= -->
		<!-- 6. 파일 업로드 관련 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/commons-io/commons-io -->
		<dependency>
		    <groupId>commons-io</groupId>
		    <artifactId>commons-io</artifactId>
		    <version>2.21.0</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- Source: https://mvnrepository.com/artifact/commons-fileupload/commons-fileupload -->
		<dependency>
		    <groupId>commons-fileupload</groupId>
		    <artifactId>commons-fileupload</artifactId>
		    <version>1.6.0</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- ================================================================================= -->
		<!-- [스프링 로그 메세지 처리] -->
		<!-- 7. 마이바티스 SQL 로그 처리하는 log4jdbc 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.bgee.log4jdbc-log4j2/log4jdbc-log4j2-jdbc4.1 -->
		<dependency>
		    <groupId>org.bgee.log4jdbc-log4j2</groupId>
		    <artifactId>log4jdbc-log4j2-jdbc4.1</artifactId>
		    <version>1.16</version>
		    <scope>compile</scope>
		</dependency>	
		
		<!-- 8. 로그 메세지를 처리하는 Log4j2 관련 라이브러리 -->
		<!-- 8-1) Apache Log4j Core 라이브러리(버전 2.x = Log4j2) -->
		<!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-core</artifactId>
<!-- 		    <version>2.25.3</version> -->
		    <version>${log4j2-version}</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- 8-2) Apache Log4j API 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-api</artifactId>
		    <version>${log4j2-version}</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- 8-3) Apache Log4j SLF4J Binding 라이브러리 -->
		<!-- 기본 로그 Slf4J -> Log4j2 로 연결해주는 역할 -->
		<!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl -->
		<dependency>
		    <groupId>org.apache.logging.log4j</groupId>
		    <artifactId>log4j-slf4j-impl</artifactId>
		    <version>${log4j2-version}</version>
		    <scope>compile</scope>
		</dependency>
		<!-- ================================================================================= -->
		<!-- 9. ChatGPT API 라이브러리 (https://github.com/openai/openai-java)--> 
		<dependency>
			<groupId>com.openai</groupId>
			<artifactId>openai-java</artifactId>
			<version>4.22.0</version>
		</dependency>
				
		<!-- ================================================================================= -->
		<!-- 10. JSON 데이터를 처리(파싱, 포맷팅)하는 Jackson 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/tools.jackson.core/jackson-core -->
		<dependency>
		    <groupId>tools.jackson.core</groupId>
		    <artifactId>jackson-core</artifactId>
		    <version>3.1.0</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- ================================================================================= -->
		<!-- 11. 자바 메일 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/com.sun.mail/javax.mail -->
		<dependency>
		    <groupId>com.sun.mail</groupId>
		    <artifactId>javax.mail</artifactId>
		    <version>1.6.2</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- Source: https://mvnrepository.com/artifact/javax.activation/activation -->
		<dependency>
		    <groupId>javax.activation</groupId>
		    <artifactId>activation</artifactId>
		    <version>1.1.1</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- 스프링에서 제공하는 메일 서포트 라이브러리(스프링 기본 버전 프로퍼티값 사용) -->
		<!-- Source: https://mvnrepository.com/artifact/org.springframework/spring-context-support -->
		<dependency>
		    <groupId>org.springframework</groupId>
		    <artifactId>spring-context-support</artifactId>
		    <version>${org.springframework-version}</version>
		    <scope>compile</scope>
		</dependency>
		
		<!-- ================================================================================= -->
		<!-- 12. 난수 생성 라이브러리 -->
		<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		    <version>3.20.0</version>
		    <scope>compile</scope>
		</dependency>		
		
		<!-- ================================================================================= -->
		<!-- AspectJ -->
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>${org.aspectj-version}</version>
		</dependency>	
		
		<!-- ================================================================================= -->
		<!-- Log4j2 라이브러리 사용 설정으로 인한 기존 Log4j 설정 주석 처리 -->
		<!-- Logging -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.slf4j</groupId> -->
<!-- 			<artifactId>slf4j-api</artifactId> -->
<!-- 			<version>${org.slf4j-version}</version> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.slf4j</groupId> -->
<!-- 			<artifactId>jcl-over-slf4j</artifactId> -->
<!-- 			<version>${org.slf4j-version}</version> -->
<!-- 			<scope>runtime</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>org.slf4j</groupId> -->
<!-- 			<artifactId>slf4j-log4j12</artifactId> -->
<!-- 			<version>${org.slf4j-version}</version> -->
<!-- 			<scope>runtime</scope> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 			<groupId>log4j</groupId> -->
<!-- 			<artifactId>log4j</artifactId> -->
<!-- 			<version>1.2.15</version> -->
<!-- 			<exclusions> -->
<!-- 				<exclusion> -->
<!-- 					<groupId>javax.mail</groupId> -->
<!-- 					<artifactId>mail</artifactId> -->
<!-- 				</exclusion> -->
<!-- 				<exclusion> -->
<!-- 					<groupId>javax.jms</groupId> -->
<!-- 					<artifactId>jms</artifactId> -->
<!-- 				</exclusion> -->
<!-- 				<exclusion> -->
<!-- 					<groupId>com.sun.jdmk</groupId> -->
<!-- 					<artifactId>jmxtools</artifactId> -->
<!-- 				</exclusion> -->
<!-- 				<exclusion> -->
<!-- 					<groupId>com.sun.jmx</groupId> -->
<!-- 					<artifactId>jmxri</artifactId> -->
<!-- 				</exclusion> -->
<!-- 			</exclusions> -->
<!-- 			<scope>runtime</scope> -->
<!-- 		</dependency> -->

		<!-- @Inject -->
		<dependency>
			<groupId>javax.inject</groupId>
			<artifactId>javax.inject</artifactId>
			<version>1</version>
		</dependency>
				
		<!-- Servlet -->
		<!-- 톰캣 9.x 버전에서는 서블릿 버전 4.x 사용 -->
		<!-- Source: https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api -->
		<dependency>
		    <groupId>javax.servlet</groupId>
		    <artifactId>javax.servlet-api</artifactId>
		    <version>4.0.1</version>
		    <scope>provided</scope>
		</dependency>
		
		<!-- JSP 버전 -->
		<!-- 톰캣 9.x 버전에서는 JSP 버전 2.3 버전까지 사용 -->
		<!-- Source: https://mvnrepository.com/artifact/javax.servlet.jsp/javax.servlet.jsp-api -->
		<dependency>
		    <groupId>javax.servlet.jsp</groupId>
		    <artifactId>javax.servlet.jsp-api</artifactId>
		    <version>2.3.3</version>
		    <scope>provided</scope>
		</dependency>

		<!-- JSTL 버전 -->
		<!-- Tomcat 10.1 버전부터는 JSTL 2.x 사용 가능하나, Tomcat 9.x 에서는 JSTL 1.2 가 안정화된 마지막 버전이다! -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>
	
		<!-- Test -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.7</version>
			<scope>test</scope>
		</dependency>        
	</dependencies>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-eclipse-plugin</artifactId>
                <version>2.9</version>
                <configuration>
                    <additionalProjectnatures>
                        <projectnature>org.springframework.ide.eclipse.core.springnature</projectnature>
                    </additionalProjectnatures>
                    <additionalBuildcommands>
                        <buildcommand>org.springframework.ide.eclipse.core.springbuilder</buildcommand>
                    </additionalBuildcommands>
                    <downloadSources>true</downloadSources>
                    <downloadJavadocs>true</downloadJavadocs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.5.1</version>
                <configuration>
                    <source>${java-version}</source>
                    <target>${java-version}</target>
                    <compilerArgument>-Xlint:all</compilerArgument>
                    <showWarnings>true</showWarnings>
                    <showDeprecation>true</showDeprecation>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.2.1</version>
                <configuration>
                    <mainClass>org.test.int1.Main</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
	